version: 1.0.{build}

branches:
  only:
  - master
#  - appveyor
  - appveyor-testbranch
  - appveyor-psx
  
skip_tags: true

configuration:
- Release

clone_folder: c:\projects\TOMB5

platform:
  - Win32
  
install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set C_INCLUDE_PATH=C:\psyq\include
  - set C_PLUS_INCLUDE_PATH=C:\psyq\include
  - set COMPILER_PATH=C:\psyq\bin
  - set G032TMP=C:\TEMP
  - set GO32=DPMISTACK 1000000
  - set LIBRARY_PATH=C:\psyq\lib
  - set PSX_PATH=C:\psyq\bin
  - set PSYQ_PATH=C:\psyq\bin
  - set TMPDIR=C:\TEMP
  - set PATH=%PATH%;C:\MinGW\bin;C:\psyq\bin;%QTDIR%\bin;%QTDIR%\Tools\mingw530_32\bin;
  - set PSYQ_SDK_URL="https://cdn.discordapp.com/attachments/396080766892638215/540669802218258443/PSYQSDK.zip"
  - appveyor DownloadFile %PSYQ_SDK_URL% -FileName PSXSDK.zip
  - 7z x PSXSDK.zip -oC:\
  
build_script:
  - cmd: mkdir C:\TEMP
  - cmd: icacls "C:\psyq" /grant Users:F
  - cmd: icacls "C:\TEMP" /grant Users:F
  - cmd: mingw32-make
  - cmd: cd DISC
  - cmd: CPE2X MAIN.CPE
  
artifacts:
   - path: DISC\*.zip
     name: Binaries
  
after_build:
  - 7z a TOMB5.zip *.EXE
  
#build: off
